{% set name = "diffsky" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/diffsky-{{ version }}.tar.gz
  sha256: 2237ecb1c0211809e775aa3ae85cc4a71c34f65943280666ab51299952533f5a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=7
    - tomli >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - jax
    - h5py
    - diffmah
    - diffstar
    - dsps

test:
  imports:
    - diffsky
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ArgonneCPAC/diffsky
  summary: Library for differentiable generation of synthetic skies
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - beckermr
